apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.qdrant.pvcname }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.qdrant.storageSize }}
  storageClassName: {{ .Values.qdrant.storageClass }}
