apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulSet.name }}
spec:
  serviceName: {{ .Values.statefulSet.serviceName }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.statefulSet.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulSet.name }}
    spec:
      containers:
        - name: qdrant
          image: {{ .Values.qdrant.image }}
          ports:
            - containerPort: 6333
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
              subPathExpr: $(HOSTNAME)

        - name: vector-loader
          image: {{ .Values.images.vectorLoaderImage }}
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: {{ .Values.configMaps.vectorLoader }}

        - name: chat-backend
          image: {{ .Values.images.chatBackendImage }}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: {{ .Values.configMaps.chatBackend }}

        - name: chat-frontend
          image: {{ .Values.images.chatFrontendImage }}
          ports:
            - containerPort: 80

      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: {{ .Values.qdrant.pvcname }}
