apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rag-app
spec:
  serviceName: "rag-app-headless"
  replicas: 2
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage/$(HOSTNAME)

        - name: vector-loader
          image: kuljotnewreg.azurecr.io/vector-loader
          ports:
            - containerPort: 5173
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for Qdrant...";
              until curl -s http://localhost:6333; do
                sleep 2;
              done;
              echo "Running embedding upsert script...";
              python /app/app.py
          envFrom:
            - configMapRef:
                name: vectorloader-config

        - name: chat-backend
          image: kuljotnewreg.azurecr.io/chat-backend
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: chatbackend-configs

        - name: chat-frontend
          image: kuljotnewreg.azurecr.io/chat-frontend
          ports:
            - containerPort: 80
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc