apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kuljot-keyvault-sync-demo
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: e549f728-1e1a-4030-8110-922a817e3233
    keyvaultName: udemydemokeyvault
    objects: |
      array:
        - objectName: AZURE-API-KEY
          objectType: secret
        - objectName: AZURE-OPENAI-ENDPOINT
          objectType: secret
        - objectName: AZURE-MODEL-NAME
          objectType: secret
    tenantId: a88f8c4d-e6b2-4ebb-b55d-4d676362bcb8